language: php

env:
  - PRODUCT=ProdA
  - PRODUCT=ProdC
  - PRODUCT=ProdD

php:
  - '7.1'
              
install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - git clone https://github.com/ngm/todoapp-aplet
  - cp eclipse/configs/$PRODUCT.config todoapp-aplet/todo.config
  - php -S localhost:8080 -t todoapp-aplet &
  - phantomjs --webdriver 4444 &
  - sleep 5

script:
  - FEATURES=$(sed 's?\(.*\)?-g \1 ?' eclipse/configs/$PRODUCT.config | tr -d '\r\n')
  - NOTFEATURES=$(comm -13 <(sort eclipse/configs/$PRODUCT.config) <(sort eclipse/configs/optionals.config) | sed 's?\(.*\)?-g Not\1 ?' | tr -d '\r\n')
  - php vendor/bin/codecept run acceptance $FEATURES $NOTFEATURES
