language: php

env:
  - PRODUCT=ProdA
  - PRODUCT=ProdB
  - PRODUCT=ProdC
  - PRODUCT=ProdD
  - PRODUCT=ProdE

php:
  - '7.1'
              
install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - git clone https://github.com/ngm/todoapp-aplet
  - cp eclipse/configs/$PRODUCT.config todoapp-aplet/todo.config
  - php -S localhost:8080 -t todoapp-aplet &
  - phantomjs --webdriver 4444 &
  - sleep 5

script:
  - FEATURES=$(sed 's?\(.*\)?-g \1 ?' eclipse/configs/$PRODUCT.config | tr -d '\r\n')
  - NOTFEATURES=$(comm -13 <(sort eclipse/configs/$PRODUCT.config) <(sort eclipse/configs/optionals.config) | sed 's?\(.*\)?-g Not\1 ?' | tr -d '\r\n')
  - php vendor/bin/codecept run acceptance $FEATURES $NOTFEATURES --html

after_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_USERNAME"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - cp tests/_output/report.html tests/_output/report$PRODUCT.html
  - git fetch origin
  - git checkout --track origin/gh-pages
  - cp tests/_output/report$PRODUCT.html .
  - git add report$PRODUCT.html
  - git commit -m "Checkin $PRODUCT test report from travis after CI run"
  - git push
