language: php

env:
  - PRODUCT=ProdA
  - PRODUCT=ProdB
  - PRODUCT=ProdC
  - PRODUCT=ProdD
  - PRODUCT=ProdE

php:
  - '7.1'

addons:
  apt:
    packages:
      - sshpass
      - python3
      - python3-pip
      - graphviz
              
install:
  - composer self-update
  - composer install --prefer-dist
  - curl -Lo travis_after_all.py https://raw.github.com/dmakhno/travis_after_all/master/travis_after_all.py

before_script:
  - git clone https://github.com/ngm/todoapp-aplet
  - cp eclipse/configs/$PRODUCT.config todoapp-aplet/todo.config
  - php -S localhost:8080 -t todoapp-aplet &
  - phantomjs --webdriver 4444 &
  - sleep 5

script:
  - FEATURES=$(sed 's?\(.*\)?-g \1 ?' eclipse/configs/$PRODUCT.config | tr -d '\r\n')
  - NOTFEATURES=$(comm -13 <(sort eclipse/configs/$PRODUCT.config) <(sort eclipse/configs/optionals.config) | sed 's?\(.*\)?-g Not\1 ?' | tr -d '\r\n')
  - php vendor/bin/codecept run acceptance $FEATURES $NOTFEATURES --html --xml


after_failure:
  - python travis_after_all.py
  - export $(cat .to_export_back)

after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)

after_script:
  # copy test report artifact to shared file storage
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -o Stricthostkeychecking=No tests/_output/report.html $DEPLOY_USER@$DEPLOY_HOST:report$PRODUCT.html 
  - sshpass -e scp -o Stricthostkeychecking=No tests/_output/report.xml $DEPLOY_USER@$DEPLOY_HOST:report$PRODUCT.xml 
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        ./build/deploy_test_artifacts.sh
      fi

# not currently using travis Build Stages as I want to execute even if a test job failed
#jobs:
# include:
#   - stage: deploy test artifacts
#     script: ./deploy_test_artifacts.sh
