language: php

env:
  - PRODUCT=ProdA

php:
  - '7.1'
              
install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - git clone https://github.com/ngm/todoapp-aplet
  - php -S localhost:8080 -t todoapp-aplet &
  - phantomjs --webdriver 4444 &
  - sleep 5

script:
  - php vendor/bin/codecept run acceptance $(sed 's?\(.*\)?-g \1 ?' eclipse/configs/ProdB.config | tr -d '\r\n')
