language: php

php:
  - '7.1'
              
install:
  - composer self-update
  - composer install --prefer-dist

before_script:
  - git clone https://github.com/ngm/todoapp-aplet
  - php -S localhost:80 -t todoapp-aplet &
  - phantomjs --webdriver 4444 &
  - sleep 5

script:
  - php vendor/bin/codecept run acceptance
